### PR TITLE
Fix imports/linting issues

### LINKED ISSUE #103: Fix pylint/ruff issues
Sigh...

### PR DESCRIPTION
**Pull request by cserver45**
This fixes #103, #146 and #150

Do not merger until @01000011-00110111 has reviewed and approved.

Do you want to save this for 1.3 or just merge it into 1.2 as some backend changes?

### CODE REVIEW

**Review by 01000011-00110111 — COMMENTED** [review]
I'd say wait until 1.3 because we basically reworking the entire backend.

**Comment by cserver45** [comment]
I say we merge this before the database branch gets merged

**Comment by cserver45** [comment]
will test after `finish_account_code` is merged, then this can merge (thats why the blocked tag is there)

**Comment by cserver45** [comment]
need to approve the review first

**Comment by 01000011-00110111** [comment]
I'll do that when I'm free

**Comment by cserver45** [comment]
ok

**Review by 01000011-00110111 — APPROVED** [review]
Love the work

**Comment by cserver45** [comment]
sigh, your branch protection rules don't let me merge because I resolved the merge conflict, if you could re-approve that would be great

**Review by 01000011-00110111 — APPROVED** [review]
I forgot what rules I put on main

**Pull request merged**
