### PR TITLE
Database rework

### LINKED ISSUE #141: Rework the database code
The current way we use the database is slow and inefficient. The plan is to improve the efficiency and speed of the code wile making it easier to add new features to the existing code.
## List to do:

- [x] build database.py
- [x] move login to new db system
- [x] move account signup to new db system
- [x] move user data retrieval to new db system
- [x] move chat rooms to new db system
- [x] move sending to new db system
~~move commands to new db system~~ #77 
- [x] move chat.py to new db system
- [x] move online list to new db system
- [x] bug fix for hours
- [x] optimize and organize
- [x] reduce amount of funcs
## extra to do:

~~improve old commands with new system~~
- [x] change the key file to a config file

### PR DESCRIPTION
**Pull request by 01000011-00110111**
Currently broken but most of the database code has been moved to one file.

resolves #141 #123

### CODE REVIEW

**Comment by 01000011-00110111** [comment]
I've been busy with work and personal things recently. I should be back soon.

**Comment by 01000011-00110111** [comment]
its not done yet Ive gotten far and now have to get the front end up to date

**Comment by cserver45** [comment]
why are you working on the new command code on the database branch?

create a new branch for the issue

**Comment by 01000011-00110111** [comment]
Can you do that for me? I'm a little busy at the moment. I should be free to work on it around 7:30

**Comment by cserver45** [comment]
sure, you also need to give me permission to edit the 1.3 project, as some stuff is marked wrong

**Comment by 01000011-00110111** [comment]
I gave you admin

**Comment by cserver45** [comment]
thanks, I have moved the commit relating to new command system to `comamnds-rework`, which is based on this branch, and not main, so the db changes still apply

**Comment by cserver45** [comment]
Current known broken commands:
(these are fixed in `commands-rework`)

- globalock
- lock
- unlock
- chat_room_edit (which is getting an overhaul it looks like)

**Review by cserver45 — APPROVED** [review]
Like the efficiency improvements, approved and merge immediately
also saw that you did #123

**Comment by cserver45** [comment]
Before you merge, you might want to update the `1.2` and `1.3` branches to match main (as they are behind iirc)

**Pull request merged**
