### PR TITLE
Finally move hyperlinks over to server-side

### LINKED ISSUE #161: Finish Hyperlink in server side
Finish Hyperlink in server side to allow sending links in chat.

### PR DESCRIPTION
**Pull request by cserver45**
This fixes #161, I finally figured out the missing piece: [regex flags, in python](https://pynative.com/python-regex-flags/)

Tested, works in my tests

DO NOT MERGE UNTIL @01000011-00110111 HAS APPROVED!

### CODE REVIEW

**Review by cserver45 — COMMENTED** [review]
And yes, I belive this is a v1.3 feature, not a v1.2 bugfix (you added back the warn system, that currently does nothing except break the old system)

**Comment by 01000011-00110111** [comment]
I was planning to add it to 1.2.2 because I need a bug fix and didn't want a small push. We can put it to 1.3 and release that small fix.

**Comment by cserver45** [comment]
If I think I know the small change you are talking about, thats actually in this PR as the first commit

**Comment by cserver45** [comment]
The only problem with that is this was forked from the `v1.3` branch, meaning that if I set the bease branch to main (v1.2), all the commits from 1.3 get integrated into main

**Review by 01000011-00110111 — APPROVED** [review]
Finally have hyperlinks fixed

**Pull request merged**
