### PR TITLE
Commands rework

### LINKED ISSUE #77: Rework commands
For example remove a user and change how refresh online list works.

### PR DESCRIPTION
**Pull request by 01000011-00110111**
The new command system revamp

resolves #77

DO NOT MERGE UNTIL @cserver45  HAS REVIEWED

### CODE REVIEW

**Review by cserver45 — COMMENTED** [review]
I would wait and test this with the new command system before we merge this. Adding the blocked tag

**Comment by 01000011-00110111** [comment]
iv tested it a few times and is on prod

**Comment by cserver45** [comment]
for some reason that wasn't linked

**Comment by cserver45** [comment]
the issue wasn't a specific cmd, it was ones that used `add_message` (because it and `log.backup_log` were still on the old system that didn't take into account different values between rooms and PMs)

**Review by cserver45 — APPROVED** [review]
I'd say it looks good now, approved

**Review by 01000011-00110111 — COMMENTED** [review]
Ive reviewed everything I agree

**Pull request merged**
